name: fingenius
description: AI-powered expense tracker with smart insights
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  
  # Authentication
  google_sign_in: ^6.1.6
  local_auth: ^2.1.6
  
  # UI & Animations
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.2.0+1
  lottie: ^2.7.0
  fl_chart: ^0.65.0
  
  # ML & AI
  google_ml_kit: ^0.16.0
  image_picker: ^1.0.4
  speech_to_text: ^6.6.0
  
  # HTTP & APIs
  http: ^1.1.0
  dio: ^5.3.2
  
  # Storage & Preferences
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  
  # PDF & Export
  pdf: ^3.10.7
  printing: ^5.11.0
  
  # Notifications
  flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
